services:
    metamodels.attribute_translatedurl.factory:
        class: MetaModels\AttributeTranslatedUrlBundle\Attribute\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@event_dispatcher'
        tags:
            - { name: metamodels.attribute_factory }

    MetaModels\AttributeTranslatedUrlBundle\Migration\AllowNullAndIndexMigration:
        arguments:
            - '@database_connection'
        tags:
            - name: contao.migration
